general {
    gaps_in = 2
    gaps_out = 4
    border_size = 2
    col.active_border = rgba(ffffffff)
    col.inactive_border = rgba(000000ff)
    layout = dwindle
}

decoration {
    rounding = 0
    shadow {
        enabled = false
    }
    blur {
        enabled = false
    }
}

input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = normal
        scroll_factor = 0.4
        tap-to-click = true
    }
    sensitivity = 0 
}

bind = SUPER SHIFT, S, exec, grim -g "$(slurp)" - | wl-copy
bind = SUPER, S, exec, grim -g "$(slurp)" ~/Pictures/$(date +'%Y-%m-%d-%H%M%S.png')
