# Force Native Wayland
--ozone-platform-hint=auto

# Force Vulkan Backend (Fixes the EGL Version Error)
--use-gl=angle
--angle-backend=vulkan
--enable-features=Vulkan,VulkanFromANGLE,DefaultANGLEVulkan

# Hardware Acceleration Fine-Tuning
--enable-features=VaapiVideoDecodeLinuxGL,VaapiVideoDecoder
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
