# --- GLOBAL SETTINGS ---
app_launch_prefix = "uwsm app --"
terminal = "kitty"
show_icons = true
width = 500
placeholder = "Void Search..."
disabled_plugins = ["archlinuxpkgs", "onepassword", "translation", "niri", "symbols"]

# --- PLUGIN LIST ---
[[plugins]]
name = "applications"
placeholder = "Applications"

[[plugins]]
name = "windows"
placeholder = "Windows"

[[plugins]]
name = "clipboard"
placeholder = "Clipboard"

[[plugins]]
name = "calc"
placeholder = "Calculator"

[[plugins]]
name = "todo"
placeholder = "Quick Notes"

# --- SPECIFIC PLUGIN CONFIGS ---
[web_search]
[[web_search.engines]]
name = "google"
url = "https://www.google.com/search?q=%s"
prefix = "g"
